version: "3.3"

services:
  blog_postgres:
    image: postgres:14
    container_name: blog_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog
