version: "3.3"

services:
  blog_postgres:
    image: postgres:14
    container_name: blog_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog
    networks:
      - blog_main_network

  blog_rabbitmq:
    container_name: blog_rabbitmq
    image: rabbitmq:latest
    restart: always
    ports:
      - "5672:5672"
    networks:
      - blog_main_network
    depends_on:
      - blog_postgres

  blog_memcached:
    container_name: blog_memcached
    image: memcached:latest
    restart: always
    ports:
      - "11211:11211"
    networks:
      - blog_main_network
    depends_on:
      - blog_postgres
      - blog_rabbitmq

networks:
  blog_main_network:
    external: true
